var GAME_LEVELS = [
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                               d                                                                              ",
   "                            yyyyyy                                                                            ",
   "                                 y                                                                            ",
   "                                 yyy                                                                          ",
   "                                    y                                                                         ",
   "                                    y                                                                         ",
   "                                    yyyyyy                                                                    ",
   "                                          yy                                                                  ",
   "                                                oo                 o                                          ",
   "                                               yyy         o          v                                       ",
   "        yyy y yyy y  y  yyy yyy y y   y yyy   y   y  yyy yyy yyy y   y  yyy  yyy yyy yyy                      ",
   "        y y y y   y y   y   y y y yy  y y         y  y y y y y   yy  y  y  y y y y y y y                      ",
   "        yyy y y   yy    y   y y y y y y yyy    yyy   y y yyy yy  y y y  y  y y y y y yyy      yy              ",
   "        y   y y   y y   y   y y y y  yy   y   y      y y y   y   y  yy  y  y y y y y y  y       yy            ",
   "  x     y   y yyy y  y  yyy yyy y y   y yyy   yyyyy  yyy y   yyy y   y  yyy  yyy yyy y  y                     ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                  yyyy     ",
   "  x   @                  o   o                                                                                ",
   "  xxxxxxx                                     xxxxx                                            yyyy           ",
   "        x     o o o o  o       o   o    o     x   xxxxxxxx   xxxxxxxxx  xxxxxxxxxxxxxxxxxxx                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                            yyyy   b   yyy                                  ",
   "                                            y     yyy          m                            ",
   "                               y         yyyy                 yy    yy                      ",
   "                               y      yyyy                     y!!!!y                       ",
   "                               yyy                             yy!!yy       m               ",
   "                                                                yyyy      xxxx              ",
   "                                                                             x              ",
   "  xx                                                                   y     x              ",
   "  x                                 yy     b         xx            xx        x              ",
   "  x          d x                 x        yyyy      xx             xx        x        d     ",
   "  x o        xxx       yy       xx                 xxx            xxx        x       xx     ",
   "  x          x    yy           xx        m        xxxx         xxxxxxx       x      xxxx  x ",
   "  x  @   m   x              xxxx       xxxxxxxxxxxxxxx!!!!!!xxxxxxxxx    xxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxx!!!!!!!!!!!!!!xxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxx!!!!!!!!!!!!!xxxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                                            ",
   "                                                                                            "],
  [
   "                                                                   xx                             ",
   "                                                                   xx                             ",
   "                                                                   xx                             ",
   "                                                                b  xx                             ",
   "                                                                   xx                             ",
   "                                       o     o                     xx                             ",
   "                                             o     y   m oo        xx                             ",
   " d                       o                          yyyyyyyyyyyyxxxxx                             ",
   "yyyyy                   yyyyy         x     x                   xxx                               ",
   "                                      x!!!!!x                   xxx                               ",
   "          y     yy              yy    xx!!!xx                   xxx                               ",
   "                                     yyxxxxxyyyyyyyyyyyyyyyyyyyyxxx                               ",
   "                                                                xxx                               ",
   "                                                  xvx           xxx                               ",
   "                                  yyy                           xxx                               ",
   "                        yy        xvx                   xxxxxxxxxxx                               ",
   "                                                        x                                         ",
   "                  x                             x      =x v                                       ",
   "                  x                             x      xx           v                             ",
   "                  x                             x       x    v                                    ",
   "                  x                             xo      x       v                             x   ",
   "                  x                             x       x                                     x   ",
   "      b           x  m x             oo         xx      x             x                       x   ",
   "       @          xxxxxx        x    xxx        x       x             x                  |    x   ",
   " m     x              xx        x  b   x  yyy   x       x   x xx xx   x                       x   ",
   "xxxxxxxx               xx       x      x        x=      x             x         |             x   ",
   "xxxxxxxx                x       x      x        x      xxx xx xx xxx  x                    =  x   ",
   "xxxxxxxx      x         x       x  y   x        x                     x   xxxxx   xxxxxx      x   ",
   "xxxxxxxx      x         x!!!!!!!x      x        xo       ooooooooooo  x                       x   ",
   "xxxxxxxx!!!!!!x         x!!v!!!xx      x!!!!!!!!xx    xxxxxxxxxxxxxxxxx     =                 x   ",
   "xxxxxxxx!!!!!!x         xxx xxvxx   y  xxxxxxxxxx!!!!!x!!!!!!!xx!!!!!!xxxxxxxxxxxxxxxx       xx   ",
   "xxxxxxxx!!!!!!x                         xx!!!!!!!!!!!xx!!!!!!xxx!!!!!!!!!!!!!!!!!!!xxxx  oo xx    ",
   "xxxxxxxx!!!!!!x                         xx!!!!!!!!!!xx!!!!!!xxxx!!!!!!!!!!!!!!!!!!!xxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x                       xxxxxxxxxxxxxxx!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x                   xxxxxxxxxxxxxxxxxxx!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x                 xxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x   oo        xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x   yy    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "xxxxxxxx!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxx     "],
   ["                                                                                                             ",
   "                                                                                                              ",
   "                     @  o   d                                                                                 ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                         ",
   "                                                                                                              ",
   "        xx    xx   xxxxxx     xx   xx                                                                         ",
   "        xx    xx  xx    xx    xx   xx                                                                         ",
   "        xx    xx  xx    xx    xx   xx                                                                         ",
   "        xxxxxxxx  xx    xx    xx   xx                                                                         ",
   "           xx     xx    xx    xx   xx                                                                         ",
   "           xx     xx    xx    xx   xx                                                                         ",
   "           xx      xxxxxx      xxxxx                                                                          ",
   "                                                                                                              ",
   "         xx        xx  xxx  xx     x                                                                          ",
   "          x   xx   x    x   xxx    x                                                                          ",
   "          xx xxxx xx    x   x xx   x                                                                          ",
   "          xx x  x xx    x   x  xx  x                                                                          ",
   "           x x  x x     x   x   xxxx                                                                          ",
   "           xxx  xxx    xxx  x     xx                                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
